### ISSUE TITLE
Signup failing

### ISSUE THREAD

**Issue by VincenzoKoestler** [jaypyles/Scraperr#31]
This looks really cool but unfortunately I cannot get it running somehow. When trying to scrape it just claims "added to queue" but nothing happens and everything else is not usable without being signed in which also fails:

```
{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at eA (https://_domain.com_/_next/static/chunks/pages/_app-ce404a7de932e067.js:21:43204)\n    at XMLHttpRequest.u (https://_domain.com_/_next/static/chunks/pages/_app-ce404a7de932e067.js:21:47852)\n    at te.request (https://_domain.com_/_next/static/chunks/pages/_app-ce404a7de932e067.js:21:55587)\n    at async f (https://_domain.com_/_next/static/chunks/pages/_app-ce404a7de932e067.js:16:75206)\n    at async b (https://_domain.com_/_next/static/chunks/pages/login-90ee17f02b6e67a5.js:1:544)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/x-www-form-urlencoded;charset=utf-8"
        },
        "method": "post",
        "url": "/api/auth/token",
        "data": "username=mail&password=password"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}```

any ideas?

**Comment by jaypyles** [comment]
I really am unsure about this one, but the new PR i just merged removes the dependency on being logged in to run jobs, so maybe try now?
