### ISSUE TITLE
There is an error in the Sqlite version，please help

### ISSUE THREAD

**Issue by wyxiong431** [jaypyles/Scraperr#53]
**Describe the bug**
There is an error in the Sqlite version. This webpage cannot function properly.
localhost did not send any data.
ERR_EMPTY_RESPONSE

**To Reproduce**
1. Install with the "docker-compose up -d" command.   
2. docker-compose.yml
services:
  scraperr:
    depends_on:
      - scraperr_api
    image: jpyles0524/scraperr:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - NEXT_PUBLIC_API_URL=http://scraperr_api:8610 # your API URL
      - SERVER_URL=http://scraperr_api:8610 # your docker container API URL
    ports:
      - 80:3000
    networks:
      - web
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - SECRET_KEY="861861" # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    container_name: scraperr_api
    ports:
      - 8610:8610
    volumes:
      - "$PWD/data:/project/data"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:

4. Visit (http://localhost:8610/) in the Chrome browser.
5. See error
This webpage cannot function properly.
localhost did not send any data.
ERR_EMPTY_RESPONSE

**Expected behavior**
Display web pages normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WINDOWS10
 - Browser chrome
 - docker desktop

**Additional context**
log
scraperr      | (node:1) ExperimentalWarning: CommonJS module /usr/local/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/local/lib/node_modules/npm/node_modules/supports-color/index.js using require().
2024-12-07 11:10:53 scraperr_api  | 2024-12-07 03:10:53,844 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
scraperr      | Support for loading ES Module in require() is an experimental feature and might change at any time
scraperr_api  | 2024-12-07 03:10:53,847 INFO supervisord started with pid 8
scraperr      | (Use `node --trace-warnings ...` to show where the warning was created)
scraperr_api  | 2024-12-07 03:10:54,850 INFO spawned: 'api' with pid 9
scraperr      | 
scraperr      | > webapp-template@0.1.0 start
scraperr      | > next start
scraperr      | 
scraperr_api  | 2024-12-07 03:10:54,851 INFO spawned: 'worker' with pid 10
scraperr_api  | 2024-12-07 03:10:55,853 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | 2024-12-07 03:10:55,853 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-07 11:10:57 scraperr      |   ▲ Next.js 14.2.4
scraperr      |   - Local:        http://localhost:3000
scraperr_api  | INFO:     Will watch for changes in these directories: ['/project']
scraperr_api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
scraperr      | 
scraperr      |  ✓ Starting...
scraperr      |  ✓ Ready in 3.1s
scraperr      | 
scraperr      | > webapp-template@0.1.0 start
scraperr_api  | INFO:     Started reloader process [17] using StatReload
scraperr      | > next start
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr      | 
scraperr      |   ▲ Next.js 14.2.4
scraperr      |   - Local:        http://localhost:3000
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr      | 
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr      |  ✓ Starting...
scraperr      |  ✓ Ready in 8.5s
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2024-12-07 03:11:03,285 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2024-12-07 03:11:04,466 INFO spawned: 'worker' with pid 22
scraperr_api  | 2024-12-07 03:11:05,468 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:     Started server process [20]
scraperr_api  | INFO:     Waiting for application startup.
scraperr_api  | INFO:     2024-12-07 03:11:06,857 - api.backend.database.startup - Executing query: CREATE TABLE IF NOT EXISTS jobs (
scraperr_api  |     id STRING PRIMARY KEY NOT NULL,
scraperr_api  |     url STRING NOT NULL,
scraperr_api  |     elements JSON NOT NULL,
scraperr_api  |     user STRING,
scraperr_api  |     time_created DATETIME NOT NULL,
scraperr_api  |     result JSON NOT NULL,
scraperr_api  |     status STRING NOT NULL,
scraperr_api  |     chat JSON,
scraperr_api  |     job_options JSON
scraperr_api  | )
scraperr_api  | INFO:     2024-12-07 03:11:06,858 - api.backend.database.startup - Executing query: 
scraperr_api  | 
scraperr_api  | CREATE TABLE IF NOT EXISTS users (
scraperr_api  |     email STRING PRIMARY KEY NOT NULL,
scraperr_api  |     hashed_password STRING NOT NULL,
scraperr_api  |     full_name STRING,
scraperr_api  |     disabled BOOLEAN
scraperr_api  | )
scraperr_api  | INFO:     2024-12-07 03:11:06,858 - api.backend.app - Starting up...
scraperr_api  | INFO:     Application startup complete.
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | 2024-12-07 04:34:29,887 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
scraperr_api  | 2024-12-07 04:34:29,995 INFO supervisord started with pid 7
scraperr_api  | 2024-12-07 04:34:30,998 INFO spawned: 'api' with pid 8
scraperr_api  | 2024-12-07 04:34:30,999 INFO spawned: 'worker' with pid 9
scraperr_api  | 2024-12-07 04:34:32,001 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | 2024-12-07 04:34:32,001 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:     Will watch for changes in these directories: ['/project']
scraperr_api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
scraperr_api  | INFO:     Started reloader process [16] using StatReload
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2024-12-07 04:34:43,165 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2024-12-07 04:34:44,168 INFO spawned: 'worker' with pid 21
scraperr_api  | 2024-12-07 04:34:45,169 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2024-12-07 04:34:46,184 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2024-12-07 04:34:47,187 INFO spawned: 'worker' with pid 26
scraperr_api  | 2024-12-07 04:34:48,188 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:     Started server process [19]
scraperr_api  | INFO:     Waiting for application startup.
scraperr_api  | INFO:     2024-12-07 04:34:48,873 - api.backend.database.startup - Executing query: CREATE TABLE IF NOT EXISTS jobs (
scraperr_api  |     id STRING PRIMARY KEY NOT NULL,
scraperr_api  |     url STRING NOT NULL,
scraperr_api  |     elements JSON NOT NULL,
scraperr_api  |     user STRING,
scraperr_api  |     time_created DATETIME NOT NULL,
scraperr_api  |     result JSON NOT NULL,
scraperr_api  |     status STRING NOT NULL,
scraperr_api  |     chat JSON,
scraperr_api  |     job_options JSON
scraperr_api  | )
scraperr_api  | INFO:     2024-12-07 04:34:48,873 - api.backend.database.startup - Executing query: 
scraperr_api  | 
scraperr_api  | CREATE TABLE IF NOT EXISTS users (
scraperr_api  |     email STRING PRIMARY KEY NOT NULL,
scraperr_api  |     hashed_password STRING NOT NULL,
scraperr_api  |     full_name STRING,
scraperr_api  |     disabled BOOLEAN
scraperr_api  | )
scraperr_api  | INFO:     2024-12-07 04:34:48,873 - api.backend.app - Starting up...
scraperr_api  | INFO:     Application startup complete.
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []
scraperr_api  | INFO:api.backend.job.job:Got queued job: []

**Comment by vikramwalia** [comment]
+1 running into the same issue.

[+] Running 3/2
 ✔ Network scraperr_web    Created                                                                               0.2s 
 ✔ Container scraperr_api  Created                                                                               0.1s 
 ✔ Container scraperr      Created                                                                               0.0s 
Attaching to scraperr, scraperr_api
scraperr_api  | 2025-04-26 01:23:14,072 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
scraperr_api  | 2025-04-26 01:23:14,082 INFO supervisord started with pid 7
scraperr      | 
scraperr      | > webapp-template@0.1.0 start
scraperr      | > next start
scraperr      | 
scraperr      |   ▲ Next.js 14.2.4
scraperr      |   - Local:        http://localhost:3000
scraperr      | 
scraperr      |  ✓ Starting...
scraperr_api  | 2025-04-26 01:23:15,084 INFO spawned: 'api' with pid 8
scraperr_api  | 2025-04-26 01:23:15,086 INFO spawned: 'worker' with pid 9
scraperr      |  ✓ Ready in 1018ms
scraperr_api  | 2025-04-26 01:23:16,088 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | 2025-04-26 01:23:16,088 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:     Will watch for changes in these directories: ['/project']
scraperr_api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
scraperr_api  | INFO:     Started reloader process [17] using StatReload
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2025-04-26 01:23:20,088 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2025-04-26 01:23:21,090 INFO spawned: 'worker' with pid 21
scraperr_api  | INFO:     Started server process [19]
scraperr_api  | INFO:     Waiting for application startup.
scraperr_api  | ERROR:    Traceback (most recent call last):
scraperr_api  |   File "/project/__pypackages__/3.10/lib/starlette/routing.py", line 692, in lifespan
scraperr_api  |     async with self.lifespan_context(app) as maybe_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/project/__pypackages__/3.10/lib/starlette/routing.py", line 569, in __aenter__
scraperr_api  |     await self._router.startup()
scraperr_api  |   File "/project/__pypackages__/3.10/lib/starlette/routing.py", line 669, in startup
scraperr_api  |     await handler()
scraperr_api  |   File "/project/api/backend/app.py", line 57, in startup_event
scraperr_api  |     start_cron_scheduler(scheduler)
scraperr_api  |   File "/project/api/backend/job/cron_scheduling/cron_scheduling.py", line 86, in start_cron_scheduler
scraperr_api  |     cron_jobs = get_all_cron_jobs()
scraperr_api  |   File "/project/api/backend/job/cron_scheduling/cron_scheduling.py", line 52, in get_all_cron_jobs
scraperr_api  |     cron_jobs = query("SELECT * FROM cron_jobs")
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: cron_jobs
scraperr_api  | 
scraperr_api  | ERROR:    Application startup failed. Exiting.
scraperr_api  | 2025-04-26 01:23:22,295 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2025-04-26 01:23:24,464 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2025-04-26 01:23:25,465 INFO spawned: 'worker' with pid 26
scraperr_api  | 2025-04-26 01:23:26,467 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2025-04-26 01:23:28,770 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2025-04-26 01:23:29,772 INFO spawned: 'worker' with pid 31
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 2/2
 ✔ Container scraperr      Stopped                                                                                                                    1.0s 
 ✔ Container scraperr_api  Stopped                                                                                                                    1.2s 
canceled


Here is the docker-compose.yml

services:
  scraperr:
    depends_on:
      - scraperr_api
    image: jpyles0524/scraperr:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - NEXT_PUBLIC_API_URL=http://scraperr_api:3034 # your API URL
      - SERVER_URL=http://scraperr_api:3034 # your docker container API URL
    ports:
      - 3033:3000
    networks:
      - web
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - SECRET_KEY=MRo9PfasPibnqFeK4Oswb6Z+PhFmjzdvxZzwdAkbf/Y= # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    container_name: scraperr_api
    ports:
      - 3034:8000
    volumes:
      - "$PWD/data:/project/data"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:

**Comment by jaypyles** [comment]
This should be fixed in the latest release
